version: '3.1'

services:
  mysql:
    image: mariadb:11.5
    ports:
      - "21312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'a3e5a6EUsVQxmAQYcyEfSDSR'
  redis:
    image: redis:7
    ports:
      - "21313:6379"
